### ISSUE TITLE
This doesn't work on Firefox Nightly

### ISSUE THREAD

**Issue by sgpthomas** [elementary/appstream-redirect#16]
I realize that this video is probably not that helpful, but I'm not sure what other information to give you. This is on nightly version 57.0a1.

![no-redirect](https://user-images.githubusercontent.com/3752122/30696978-725feaa6-9eab-11e7-93bc-46f0aeeb4540.gif)

**Comment by arshubham** [comment]
@sgpthomas  Is this still a issue. I remember it not working on nightly 57, but now on nightly 60 it works perfectly and asks for the the application to handle appstream links

**Comment by lewisgoddard** [comment]
If it works in stable I'll close the issue.

**Comment by lewisgoddard** [comment]
Seems to work fine on Firefox Stable 58 and Firefox Nightly 60. We can always re-open if someone can point to a current Browser/OS combo that doesn't do what it should.
